/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_klniu_xiaoyi_XFJNI_Iat */

#ifndef _Included_com_klniu_xiaoyi_XFJNI_Iat
#define _Included_com_klniu_xiaoyi_XFJNI_Iat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_klniu_xiaoyi_XFJNI_Iat
 * Method:    uploadHotWords
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_klniu_xiaoyi_XFJNI_Iat_uploadHotWords
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
